# Generated by Django 4.2.17 on 2025-07-24 14:57

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    Parameter = apps.get_model("api_app", "Parameter")
    AnalyzerConfig = apps.get_model("analyzers_manager", "AnalyzerConfig")

    pm = PythonModule.objects.get(
        module="capa_info.CapaInfo",
        base_path="api_app.analyzers_manager.file_analyzers",
    )

    AnalyzerConfig.objects.filter(python_module=pm).update(soft_time_limit=1800)

    p1 = Parameter(
        name="timeout",
        type="float",
        description="Duration in seconds for which intelowl waits for capa to return results. Default is set to 15 seconds.",
        is_secret=False,
        required=False,
        python_module=pm,
    )

    p1.full_clean()
    p1.save()


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers_manager", "0163_analyzer_config_guarddoggeneric"),
    ]

    operations = [migrations.RunPython(migrate, migrations.RunPython.noop)]
